# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: huiya123
  # 连接redis
  redis:
    host: 192.168.43.214
# 开启驼峰命名法匹配规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# 打印sql语句
logging:
  level:
    com:
      muc:
        cache:
          mapper: debug
# 指定端口
server:
  port: 8888

# 配置报告
#debug:  true


